name: Java CI pipeline
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven 
    - name: Build with Maven
      run: mvn clean package
    - name: Upload Artifact 
      uses: actions/upload-artifact@v3
      with:
        name: spring-petclinic
        path: "/target/spring-petclinic-2.4.5.jar"
